### ISSUE TITLE
I can't resume preview canvas

### ISSUE THREAD

**Issue by JiangYiWork** [ra1028/SwiftUI-Combine-Example#1]
My environment is ok, as my new initial project with SwiftUI can resume preview canvas. But, in this project, I can't see preview canvas.

When I add below section: 

```
#if DEBUG  
struct ContentView_Previews : PreviewProvider {  
    static var previews: some View {  
        SearchUserView()  
    }  
}  
#endif  
```

I got: 

> SwiftUI-Combine-Example.app: Error Domain=render service Code=12 "Rendering service was interrupted" UserInfo={NSLocalizedDescription=Rendering service was interrupted}

**Comment by bfernandesbfs** [comment]
Are you using MacOS Catalina?

**Comment by jiang-yi-siphty** [comment]
Yes, I am using the Beta MacOS. :(

**Comment by AbsolutelyRyann** [comment]
How did you resolve this?
